package orchi.HHCloud.share;

/**
 *  <pre>
 *      (P) PUBLICO (COMPARTIDOS CON LOS Q TENGAN EL ENALCE)
 *      (U) COMPARTIDO A USUARIOS ESPESIFICOS
 *      (W) COMPARTIR EN PUBLICO Y A USUARIOS ESPESIFICOS
 *  </pre>*/
public enum Mode {
    /**(P) PUBLICO (COMPARTIDOS CON LOS Q TENGAN EL ENALCE)*/
    P,
    /**(U) COMPARTIDO SOLO A USUARIOS ESPESIFICOS*/
    U,
    /**(W) COMPARTIR EN PUBLICO Y A USUARIOS ESPESIFICOS*/
    W;
}
