connect 'jdbc:derby:db/HHCloud;create=true';  --comentar esta linea si no es se ejecutara en la base de datos embebida

CREATE TABLE USERS
    (ID varchar(100) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    EMAILVERIFIED BOOLEAN NOT NULL,
    USERNAME varchar(100)  NOT NULL,
    FIRSTNAME varchar(100) NOT NULL,
    LASTNAME varchar(100) NOT NULL,
    GENDER varchar (1) NOT NULL, --f,m,n
    CREATEAT BIGINT NOT NULL,
    PASS varchar(1000)  NOT NULL);

CREATE UNIQUE INDEX uid ON USERS (ID);

CREATE UNIQUE INDEX email ON USERS (EMAIL);

CREATE UNIQUE INDEX username ON USERS (USERNAME);

CREATE TABLE USER_AVAILABLE(
    IDUSER VARCHAR(100) NOT NULL,
    REASON VARCHAR(1000) NOT NULL,
    CREATEDAT BIGINT NOT NULL
);

CREATE UNIQUE INDEX UAID ON USER_AVAILABLE (IDUSER);
insert into USER_AVAILABLE values ('123','por mmg',123124123);
--INSERT INTO USERS VALUES
--('123', 'luisa@gmail.com', true, 'luisa.s','luisa','gomes','f', 1533252085955,'AUQk/iNJ+0h0xfHhyTwlUVuIXu7VofOHaS9J1HOtbvrd9KQmcNK7mlk='),
--('1234', 'david@gmail.com', true, 'david.c', 'david','colmenares','m',1533252085955,'AUQk/iNJ+0h0xfHhyTwlUVuIXu7VofOHaS9J1HOtbvrd9KQmcNK7mlk=');

-- ROLES: (ADMIN, USER), por el momento solo sera usado por el administrador
CREATE TABLE ROLES (
    IDUSER varchar(100) not null,
    ROLE varchar(10) not null
);

CREATE UNIQUE INDEX RUID ON ROLES (IDUSER);

CREATE TABLE SHAREDPARENT
    (PATH VARCHAR (10000) NOT NULL,
    CSPATH varchar(10000) not null ,
    OWNERUSER VARCHAR(100) NOT NULL);

CREATE  INDEX SPPATH ON SHAREDPARENT (PATH);
CREATE  INDEX SPOWNERUSER ON SHAREDPARENT (OWNERUSER);
CREATE  INDEX SPOWNERUSER ON CSPATH (CSPATH);

CREATE TABLE SHARE
    (
    PATH VARCHAR(10000) NOT NULL,
    OWNERUSER VARCHAR(100) NOT NULL,
    PPATH VARCHAR(10000) NOT NULL,
    CREATEAT BIGINT NOT NULL);

-- CREATE INDEX CID ON SHARE (CID);
CREATE INDEX PATH ON SHARE (PATH);
CREATE INDEX OWNERUSER ON SHARE (OWNERUSER);
CREATE INDEX PPATH ON SHARE (PPATH);


SELECT SHARE.* FROM SHARE LEFT JOIN SHAREDPARENT
    ON SHARE.PPATH = SHAREDPARENT.PATH
    WHERE SHAREDPARENT.PATH = '/respaldo';


CREATE TABLE SPACE_QUOTA (
    IDUSER varchar(100) NOT NULL,
    SIZE BIGINT NOT NULL
);

CREATE UNIQUE INDEX TOUSER ON SPACE_QUOTA (IDUSER);