connect 'jdbc:derby:db/HHCloud;create=true';

CREATE TABLE USERS
    (ID varchar(100) NOT NULL,
    EMAIL varchar(100) NOT NULL,
    EMAILVERIFIED BOOLEAN NOT NULL,
    USERNAME varchar(100)  NOT NULL,
    FIRSTNAME varchar(100) NOT NULL,
    LASTNAME varchar(100) NOT NULL,
    GENDER varchar (1) NOT NULL, --f,m,n
    CREATEAT BIGINT NOT NULL,
    PASS varchar(100)  NOT NULL);

CREATE UNIQUE INDEX uid ON USERS (ID);

CREATE UNIQUE INDEX email ON USERS (EMAIL);

CREATE UNIQUE INDEX username ON USERS (USERNAME);

INSERT INTO USERS VALUES
('123', 'luisa@gmail.com', true, 'luisa.s','luisa','gomes','f', 1533252085955,'2525'),
('1234', 'david@gmail.com', true, 'david.c', 'david','colmenares','m',1533252085955,'2525');

CREATE TABLE SHAREBYUSER
    (IDUSER VARCHAR(100) NOT NULL,
    IDSHARE VARCHAR(100) NOT NULL);

CREATE TABLE SHAREBYPATH
    (PATH BLOB(500K) NOT NULL,
    IDSHARE VARCHAR(100) NOT NULL);

CREATE TABLE SHARE
    (ID VARCHAR(100) NOT NULL,
    PATH BLOB(500K) NOT NULL,
    OWNERUSER VARCHAR(100) NOT NULL,
    CREATEAT BIGINT NOT NULL);





